# Generated by Django 2.0.3 on 2018-03-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20180311_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupaccessforgroup',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='groupaccessforuser',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='manuallyfilledgroup',
            options={'base_manager_name': 'objects'},
        ),
    ]
