# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    replaces = [('questionnaire', '0001_initial'), ('questionnaire', '0002_auto_20160324_1511'), ('questionnaire', '0003_auto_20160324_1542'), ('questionnaire', '0004_auto_20160324_1800'), ('questionnaire', '0005_auto_20160325_0105'), ('questionnaire', '0006_auto_20160328_0243'), ('questionnaire', '0007_auto_20160328_1223'), ('questionnaire', '0008_auto_20160328_1720'), ('questionnaire', '0009_auto_20160426_2151'), ('questionnaire', '0010_auto_20160515_1808'), ('questionnaire', '0011_auto_20160515_2339'), ('questionnaire', '0012_auto_20160519_1402'), ('questionnaire', '0013_auto_20160522_1904'), ('questionnaire', '0014_abstractquestionnairequestion_is_disabled'), ('questionnaire', '0015_auto_20160725_1510')]

    dependencies = [
        ('schools', '0002_auto_20160320_1808'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Идентификатор. Лучше сделать из английских букв, цифр и подчёркивания', max_length=100)),
                ('text', models.CharField(help_text='Вопрос', max_length=100)),
                ('is_required', models.BooleanField(help_text='Является ли вопрос обязательным')),
                ('help_text', models.CharField(blank=True, help_text='Подсказка, помогающая ответить на вопрос', max_length=400)),
                ('Порядок', models.IntegerField(default=0, help_text='Вопросы выстраиваются по возрастанию порядка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestionnaireQuestionVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questionnaire.ChoiceQuestionnaireQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Используется для урлов. Лучше обойтись латинскими букваи, цифрами и подчёркиванием', max_length=100)),
                ('title', models.CharField(help_text='Название анкеты', max_length=100)),
                ('for_school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
                ('for_session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Session')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Идентификатор. Лучше сделать из английских букв, цифр и подчёркивания', max_length=100)),
                ('text', models.TextField(help_text='Вопрос')),
                ('is_required', models.BooleanField(help_text='Является ли вопрос обязательным')),
                ('help_text', models.CharField(blank=True, help_text='Подсказка, помогающая ответить на вопрос', max_length=400)),
                ('order', models.IntegerField(default=0, help_text='Вопросы выстраиваются по возрастанию порядка')),
                ('is_multiline', models.BooleanField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textquestionnairequestion_questions', to='questionnaire.Questionnaire')),
                ('fa', models.CharField(blank=True, help_text='Имя иконки FontAwesome, которую нужно показать в поле', max_length=20)),
                ('placeholder', models.TextField(blank=True, help_text='Подсказка, показываемая в поле для ввода; пример')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YesNoQuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Идентификатор. Лучше сделать из английских букв, цифр и подчёркивания', max_length=100)),
                ('text', models.TextField(help_text='Вопрос')),
                ('is_required', models.BooleanField(help_text='Является ли вопрос обязательным')),
                ('help_text', models.CharField(blank=True, help_text='Подсказка, помогающая ответить на вопрос', max_length=400)),
                ('order', models.IntegerField(default=0, help_text='Вопросы выстраиваются по возрастанию порядка')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yesnoquestionnairequestion_questions', to='questionnaire.Questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='choicequestionnairequestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicequestionnairequestion_questions', to='questionnaire.Questionnaire'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together=set([('for_school', 'short_name')]),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='for_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='for_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Session'),
        ),
        migrations.RenameField(
            model_name='choicequestionnairequestion',
            old_name='Порядок',
            new_name='order',
        ),
        migrations.AddField(
            model_name='choicequestionnairequestion',
            name='is_inline',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choicequestionnairequestion',
            name='is_multiple',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choicequestionnairequestion',
            name='text',
            field=models.TextField(help_text='Вопрос'),
        ),
        migrations.AlterUniqueTogether(
            name='choicequestionnairequestion',
            unique_together=set([('short_name', 'questionnaire')]),
        ),
        migrations.AlterUniqueTogether(
            name='textquestionnairequestion',
            unique_together=set([('short_name', 'questionnaire')]),
        ),
        migrations.AlterUniqueTogether(
            name='yesnoquestionnairequestion',
            unique_together=set([('short_name', 'questionnaire')]),
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_short_name', models.CharField(max_length=100)),
                ('answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionnaireStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'NOT FILLED'), (2, 'FILLED')], validators=[djchoices.choices.ChoicesValidator({1: 'NOT FILLED', 2: 'FILLED'})])),
            ],
            options={
                'verbose_name_plural': 'User questionnaire statuses',
            },
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='short_name',
            field=models.CharField(help_text='Используется для урлов. Лучше обойтись латинскими буквами, цифрами и подчёркиванием', max_length=100),
        ),
        migrations.AddField(
            model_name='userquestionnairestatus',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='userquestionnairestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaireanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userquestionnairestatus',
            unique_together=set([('user', 'questionnaire')]),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireanswer',
            unique_together=set([]),
        ),
        migrations.AlterField(
            model_name='userquestionnairestatus',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='questionnaire.Questionnaire'),
        ),
        migrations.AlterIndexTogether(
            name='questionnaireanswer',
            index_together=set([('questionnaire', 'user', 'question_short_name')]),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='close_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='short_name',
            field=models.CharField(help_text='Используется в урлах. Лучше обойтись латинскими буквами, цифрами и подчёркиванием', max_length=100),
        ),
        migrations.CreateModel(
            name='DateQuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Идентификатор. Лучше сделать из английских букв, цифр и подчёркивания', max_length=100)),
                ('text', models.TextField(help_text='Вопрос')),
                ('is_required', models.BooleanField(help_text='Является ли вопрос обязательным')),
                ('help_text', models.CharField(blank=True, help_text='Подсказка, помогающая ответить на вопрос', max_length=400)),
                ('order', models.IntegerField(default=0, help_text='Вопросы выстраиваются по возрастанию порядка')),
                ('with_year', models.BooleanField(default=True)),
                ('min_year', models.PositiveIntegerField(null=True)),
                ('max_year', models.PositiveIntegerField(null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datequestionnairequestion_questions', to='questionnaire.Questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='datequestionnairequestion',
            unique_together=set([('short_name', 'questionnaire')]),
        ),
        migrations.CreateModel(
            name='AbstractQuestionnaireBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Используется в урлах. Лучше обойтись латинскими буквами, цифрами и подчёркиванием', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Блоки выстраиваются по возрастанию порядка')),
            ],
            options={
                'ordering': ('questionnaire_id', 'order'),
            },
        ),
        migrations.CreateModel(
            name='AbstractQuestionnaireQuestion',
            fields=[
                ('abstractquestionnaireblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.AbstractQuestionnaireBlock')),
                ('text', models.TextField(help_text='Вопрос')),
                ('is_required', models.BooleanField(help_text='Является ли вопрос обязательным')),
                ('help_text', models.CharField(blank=True, help_text='Подсказка, помогающая ответить на вопрос', max_length=400)),
            ],
            options={
                'abstract': False,
            },
            bases=('questionnaire.abstractquestionnaireblock',),
        ),
        migrations.CreateModel(
            name='QuestionnaireBlockShowCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='choicequestionnairequestion',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='datequestionnairequestion',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='textquestionnairequestion',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='yesnoquestionnairequestion',
            unique_together=set([]),
        ),
        migrations.CreateModel(
            name='MarkdownQuestionnaireBlock',
            fields=[
                ('abstractquestionnaireblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.AbstractQuestionnaireBlock')),
                ('markdown', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('questionnaire.abstractquestionnaireblock',),
        ),
        migrations.RemoveField(
            model_name='choicequestionnairequestionvariant',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='choicequestionnairequestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='datequestionnairequestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='yesnoquestionnairequestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='textquestionnairequestion',
            name='id',
        ),
        migrations.AddField(
            model_name='questionnaireblockshowcondition',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_conditions', to='questionnaire.AbstractQuestionnaireBlock'),
        ),
        migrations.AddField(
            model_name='questionnaireblockshowcondition',
            name='need_to_be_checked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.ChoiceQuestionnaireQuestionVariant'),
        ),
        migrations.AddField(
            model_name='abstractquestionnaireblock',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_questionnaire.abstractquestionnaireblock_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='abstractquestionnaireblock',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
        ),
        migrations.AddField(
            model_name='choicequestionnairequestion',
            name='abstractquestionnairequestion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.AbstractQuestionnaireQuestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datequestionnairequestion',
            name='abstractquestionnairequestion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.AbstractQuestionnaireQuestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textquestionnairequestion',
            name='abstractquestionnairequestion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.AbstractQuestionnaireQuestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yesnoquestionnairequestion',
            name='abstractquestionnairequestion_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.AbstractQuestionnaireQuestion'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='choicequestionnairequestion',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='choicequestionnairequestion',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='choicequestionnairequestion',
            name='order',
        ),
        migrations.RemoveField(
            model_name='choicequestionnairequestion',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='choicequestionnairequestion',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='choicequestionnairequestion',
            name='text',
        ),
        migrations.RemoveField(
            model_name='datequestionnairequestion',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='datequestionnairequestion',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='datequestionnairequestion',
            name='order',
        ),
        migrations.RemoveField(
            model_name='datequestionnairequestion',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='datequestionnairequestion',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='datequestionnairequestion',
            name='text',
        ),
        migrations.RemoveField(
            model_name='textquestionnairequestion',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='textquestionnairequestion',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='textquestionnairequestion',
            name='order',
        ),
        migrations.RemoveField(
            model_name='textquestionnairequestion',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='textquestionnairequestion',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='textquestionnairequestion',
            name='text',
        ),
        migrations.RemoveField(
            model_name='yesnoquestionnairequestion',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='yesnoquestionnairequestion',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='yesnoquestionnairequestion',
            name='order',
        ),
        migrations.RemoveField(
            model_name='yesnoquestionnairequestion',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='yesnoquestionnairequestion',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='yesnoquestionnairequestion',
            name='text',
        ),
        migrations.AlterUniqueTogether(
            name='abstractquestionnaireblock',
            unique_together=set([('short_name', 'questionnaire'), ('questionnaire', 'order')]),
        ),
        migrations.AddField(
            model_name='choicequestionnairequestionvariant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questionnaire.ChoiceQuestionnaireQuestion'),
        ),
        migrations.AddField(
            model_name='choicequestionnairequestionvariant',
            name='disable_question_if_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choicequestionnairequestionvariant',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abstractquestionnairequestion',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Выключена ли возможность ответить на вопрос. Не может быть отмечено одновременно с is_required'),
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='for_session',
            new_name='session',
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together=set([('school', 'short_name')]),
        ),
    ]
