# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial_squashed_0015_auto_20160725_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireanswer',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnaireanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
