# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('questionnaire', '0001_initial_squashed_0015_auto_20160725_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquestionnairestatus',
            options={'verbose_name_plural': 'user questionnaire statuses'},
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='must_fill',
            field=models.ForeignKey(blank=True, default=None, help_text='Группа пользователей, которые должны заполнить эту анкету.Если не указано, то считается, что никто не должен', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='groups.ManuallyFilledGroup'),
        ),
    ]
