# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20171204_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='must_fill',
            field=models.ForeignKey(blank=True, default=None, help_text='Группа пользователей, которые должны заполнить эту анкету.Если не указано, то считается, что никто не должен', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='groups.AbstractGroup'),
        ),
    ]
