# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('questionnaire', '0003_auto_20171204_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFilledQuestionnaireGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('questionnaire', models.ForeignKey(help_text='Анкета, заполнившие которую пользователи автоматически попадут в эту группу', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Questionnaire')),
            ],
            options={
                'abstract': False,
            },
            bases=('groups.abstractgroup',),
        ),
        migrations.CreateModel(
            name='UsersNotFilledQuestionnaireGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('questionnaire', models.ForeignKey(help_text='Анкета, незаполнившие которую пользователи автоматически попадут в эту группу. Для анкеты должно быть установлено поле must_fill', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Questionnaire')),
            ],
            options={
                'abstract': False,
            },
            bases=('groups.abstractgroup',),
        ),
    ]
