# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_usersfilledquestionnairegroup_usersnotfilledquestionnairegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfilledquestionnairegroup',
            name='questionnaire',
            field=models.ForeignKey(help_text='В группу автоматически попадут все пользователи, заполнившие эту анкету', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='usersnotfilledquestionnairegroup',
            name='questionnaire',
            field=models.ForeignKey(help_text='В группу автоматически попадут все пользователи, НЕ заполнившие эту анкету. Для анкеты должно быть установлено поле must_fill', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Questionnaire'),
        ),
    ]
