# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20170521_2149'),
        ('questionnaire', '0005_questionnaire_enable_autofocus'),
    ]

    operations = [
    ]
