# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-02 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_use_dates_app_2_20171114_2309'),
        ('questionnaire', '0005_auto_20180224_2336'),
    ]

    operations = [
    ]
