# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_merge_20180302_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractquestionnaireblock',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='questionnaire.Questionnaire'),
        ),
    ]
