# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20160426_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateQuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Идентификатор. Лучше сделать из английских букв, цифр и подчёркивания', max_length=100)),
                ('text', models.CharField(help_text='Вопрос', max_length=100)),
                ('is_required', models.BooleanField(help_text='Является ли вопрос обязательным')),
                ('help_text', models.CharField(blank=True, help_text='Подсказка, помогающая ответить на вопрос', max_length=400)),
                ('order', models.IntegerField(default=0, help_text='Вопросы выстраиваются по возрастанию порядка')),
                ('with_year', models.BooleanField(default=True)),
                ('min_year', models.PositiveIntegerField(null=True)),
                ('max_year', models.PositiveIntegerField(null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datequestionnairequestion_questions', to='questionnaire.Questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='datequestionnairequestion',
            unique_together=set([('short_name', 'questionnaire')]),
        ),
    ]
