# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-25 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_1_make_variant_orders_unique_20180302_2225'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choicequestionnairequestionvariant',
            unique_together=set([('question', 'order')]),
        ),
    ]
