# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20160515_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestionnairequestion',
            name='text',
            field=models.TextField(help_text='Вопрос'),
        ),
        migrations.AlterField(
            model_name='choicequestionnairequestionvariant',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datequestionnairequestion',
            name='text',
            field=models.TextField(help_text='Вопрос'),
        ),
        migrations.AlterField(
            model_name='textquestionnairequestion',
            name='text',
            field=models.TextField(help_text='Вопрос'),
        ),
        migrations.AlterField(
            model_name='yesnoquestionnairequestion',
            name='text',
            field=models.TextField(help_text='Вопрос'),
        ),
    ]
