# Generated by Django 2.0.3 on 2018-03-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_2_auto_20180302_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractquestionnairequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='choicequestionnairequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='datequestionnairequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='markdownquestionnaireblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='textquestionnairequestion',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='usersfilledquestionnairegroup',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='usersnotfilledquestionnairegroup',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='yesnoquestionnairequestion',
            options={'base_manager_name': 'objects'},
        ),
    ]
