# Generated by Django 2.0.3 on 2018-04-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20180312_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineQuestionnaireBlock',
            fields=[
                ('abstractquestionnaireblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.AbstractQuestionnaireBlock')),
                ('text', models.TextField(blank=True, help_text='Общий текст для вопросов в блоке')),
                ('help_text', models.CharField(blank=True, help_text='Подсказка, помогающая ответить на вопросы в блоке', max_length=400)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('questionnaire.abstractquestionnaireblock',),
        ),
        migrations.CreateModel(
            name='InlineQuestionnaireBlockChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(help_text='Вопрос, вложенный в InlineBlock', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.AbstractQuestionnaireQuestion')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questionnaire.InlineQuestionnaireBlock')),
            ],
        ),
        migrations.AddField(
            model_name='abstractquestionnaireblock',
            name='is_top_level',
            field=models.BooleanField(default=True, help_text='True, если блок находится на верхнем уровне вложенности'),
        ),
    ]
