# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20160519_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestionnairequestionvariant',
            name='disable_question_if_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choicequestionnairequestionvariant',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
