# Generated by Django 2.0.3 on 2018-04-02 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20180402_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinequestionnaireblockchild',
            name='md_width',
            field=models.IntegerField(default=6, help_text='Размер на остальных устройствах. От 1 до 12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='inlinequestionnaireblockchild',
            name='sm_width',
            field=models.IntegerField(default=12, help_text='Размер на устройствах шириной от 768 до 992 пикселей. От 1 до 12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='inlinequestionnaireblockchild',
            name='xs_width',
            field=models.IntegerField(default=12, help_text='Размер на телефонах. От 1 до 12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
