# Generated by Django 2.0.3 on 2018-05-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('questionnaire', '0013_auto_20180402_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListQuestionnaireQuestion',
            fields=[
                ('abstractquestionnairequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.AbstractQuestionnaireQuestion')),
                ('placeholder', models.TextField(blank=True, help_text='Подсказка, показываемая в поле для ввода; пример')),
                ('group', models.ForeignKey(help_text='Группа, пользователей которой можно выбирать', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup')),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
            bases=('questionnaire.abstractquestionnairequestion',),
        ),
    ]
