# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20160522_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractquestionnairequestion',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='Выключена ли возможность ответить на вопрос. Не может быть отмечено одновременно с is_required'),
        ),
    ]
