# Generated by Django 2.0.3 on 2018-06-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('questionnaire', '0014_userlistquestionnairequestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionnaireBlockShowCondition',
            new_name='QuestionnaireBlockVariantCheckedShowCondition'
        ),
        migrations.AlterField(
            model_name='questionnaireblockvariantcheckedshowcondition',
            name='need_to_be_checked',
            field=models.ForeignKey(help_text='Вариант, который должен быть отмечен', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.ChoiceQuestionnaireQuestionVariant'),
        ),
        migrations.AlterField(
            model_name='questionnaireblockvariantcheckedshowcondition',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_conditions_questionnaireblockvariantcheckedshowcondition', to='questionnaire.AbstractQuestionnaireBlock'),
        ),
        migrations.CreateModel(
            name='QuestionnaireBlockGroupMemberShowCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='show_conditions_questionnaireblockgroupmembershowcondition',
                                            to='questionnaire.AbstractQuestionnaireBlock')),
                ('need_to_be_member', models.ForeignKey(help_text='Группа, участником которой должен быть пользователь',
                                                        on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                                        to='groups.AbstractGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
