# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_abstractquestionnairequestion_is_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='for_session',
            new_name='session',
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together=set([('school', 'short_name')]),
        ),
    ]
