# Generated by Django 2.0.3 on 2018-11-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20180603_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlistquestionnairequestion',
            name='group',
            field=models.ForeignKey(help_text='Группа, пользователей которой можно выбирать', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup'),
        ),
    ]
