# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poldnev', '0002_auto_20170126_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='poldnev_id',
            field=models.IntegerField(help_text='Id человека на poldnev.ru. Заполняется автоматически командой manage.py update_poldnev по информации с сайта.', unique=True),
        ),
    ]
