# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poldnev', '0004_auto_20170219_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='Имя человека на poldnev.ru. Заполняется автоматически командой manage.py update_poldnev по информации с сайта.', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='Фамилия человека на poldnev.ru. Заполняется автоматически командой manage.py update_poldnev по информации с сайта.', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(help_text='Отчество человека на poldnev.ru. Заполняется автоматически командой manage.py update_poldnev по информации с сайта.', max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(help_text='Имя смены на poldnev.ru. Заполняется автоматически командой manage.py update_poldnev по информации с сайта.', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='poldnev_id',
            field=models.CharField(help_text='Id смены на poldnev.ru. Заполняется автоматически командой manage.py update_poldnev по информации с сайта.', max_length=50, unique=True),
        ),
    ]
