# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poldnev', '0005_auto_20170219_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryEntry',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
