# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poldnev', '0007_auto_20170318_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryEntry',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
