# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20170223_2302'),
        ('poldnev', '0008_auto_20170323_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Роль. Пустая для школьников', max_length=150, blank=True)),
                ('person', models.ForeignKey(help_text='Человек', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='poldnev.Person')),
                ('session', models.ForeignKey(help_text='Смена', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='poldnev.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Parallel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=100)),
                ('schools_parallel', models.ForeignKey(blank=True, help_text='Параллель из модуля schools, соответствующая этой параллели на poldnev.ru', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poldnev_parallels', to='schools.Parallel')),
                ('session', models.ForeignKey(help_text='Смена', on_delete=django.db.models.deletion.CASCADE, related_name='parallels', to='poldnev.Session')),
            ],
            options={
                'ordering': ('session', 'name'),
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=100)),
                ('parallel', models.ForeignKey(help_text='Параллель', on_delete=django.db.models.deletion.CASCADE, related_name='study_groups', to='poldnev.Parallel')),
            ],
            options={
                'ordering': ('parallel', 'name'),
            },
        ),
        migrations.AddField(
            model_name='historyentry',
            name='study_group',
            field=models.ForeignKey(blank=True, help_text='Учебная группа. Может отсутствовать, например, для врача', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='poldnev.StudyGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='studygroup',
            unique_together=set([('parallel', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='parallel',
            unique_together=set([('session', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='historyentry',
            unique_together=set([('session', 'study_group', 'role', 'person')]),
        ),
    ]
