# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_topicquestionnaire_close_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicquestionnaire',
            old_name='for_school',
            new_name='school',
        ),
    ]
