# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20160725_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set([('questionnaire', 'name')]),
        ),
    ]
