# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('smartq', '0002_auto_20170318_2159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0004_auto_20160725_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartqQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'IN PROGRESS'), (2, 'REFUSED'), (3, 'FAILED'), (4, 'PASSED')], validators=[djchoices.choices.ChoicesValidator({1: 'IN PROGRESS', 2: 'REFUSED', 3: 'FAILED', 4: 'PASSED'})])),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topics.TopicQuestionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartqQuestionnaireQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker_result', models.PositiveIntegerField(choices=[(1, 'OK'), (2, 'WRONG ANSWER'), (3, 'PRESENTATION ERROR'), (4, 'CHECK FAILED')], default=None, null=True, validators=[djchoices.choices.ChoicesValidator({1: 'OK', 2: 'WRONG ANSWER', 3: 'PRESENTATION ERROR', 4: 'CHECK FAILED'})])),
                ('checker_message', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='smartq.GeneratedQuestion')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.SmartqQuestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='TopicQuestionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=None, null=True)),
                ('group', models.IntegerField(blank=True, default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_mapping', to='smartq.Question')),
                ('scale_in_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartq_mapping', to='topics.ScaleInTopic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicSmartqSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_questions', models.PositiveIntegerField()),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.TopicQuestionnaire')),
            ],
        ),
        migrations.AlterField(
            model_name='userquestionnairestatus',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'NOT STARTED'), (2, 'STARTED'), (3, 'CORRECTING'), (4, 'FINISHED'), (5, 'CHECK TOPICS')], validators=[djchoices.choices.ChoicesValidator({1: 'NOT STARTED', 2: 'STARTED', 3: 'CORRECTING', 4: 'FINISHED', 5: 'CHECK TOPICS'})]),
        ),
        migrations.AddField(
            model_name='smartqquestionnairequestion',
            name='topic_mapping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topics.TopicQuestionMapping'),
        ),
    ]
