# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('topics', '0005_filltopicsquestionnaireentrancestep'), ('topics', '0006_auto_20170316_1910'), ('topics', '0007_auto_20170316_2009')]

    dependencies = [
        ('entrance', '0026_auto_20170312_0128'),
        ('topics', '0004_auto_20160725_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillTopicsQuestionnaireEntranceStep',
            fields=[
                ('abstractentrancestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.AbstractEntranceStep')),
                ('text_before_start_date', models.TextField(blank=True, help_text='Текст, который показывается до даты начала заполнения шага. Поддерживается Markdown')),
                ('text_after_finish_date', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения. Поддерживается Markdown')),
                ('text_waiting_for_other_step', models.TextField(blank=True, help_text='Текст, который показывается, когда не пройден один изпредыдущих шагов. Поддерживается Markdown')),
                ('text_step_is_not_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг ещё не пройден. Поддерживается Markdown')),
                ('text_step_is_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг пройден пользователем. Поддерживается Markdown')),
                ('questionnaire', models.ForeignKey(help_text='Тематическая анкета, которую нужно заполнить', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topics.TopicQuestionnaire')),
                ('text_questionnaire_correcting', models.TextField(blank=True, help_text='Текст, который показывается, когда пользователь не подтвердил оценки. Поддерживается Markdown')),
                ('text_questionnaire_not_finished', models.TextField(blank=True, help_text='Текст, который показывается, когда анкета недозаполнена. Поддерживается Markdown')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.abstractentrancestep', models.Model),
        ),
    ]
