# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20170322_0040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartqQuestionnaire',
            new_name='TopicCheckingQuestionnaire',
        ),
        migrations.RenameModel(
            old_name='SmartqQuestionnaireQuestion',
            new_name='TopicCheckingQuestionnaireQuestion',
        ),
        migrations.RenameModel(
            old_name='TopicSmartqSettings',
            new_name='TopicCheckingSettings',
        ),
    ]
