# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    # Django 2.0 requires this for renaming models in SQLite
    # https://stackoverflow.com/questions/48549068/django-db-utils-notsupportederror-in-sqlite-why-not-supported-in-sqlite
    atomic = False

    dependencies = [
        ('topics', '0006_auto_20170322_0040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartqQuestionnaire',
            new_name='TopicCheckingQuestionnaire',
        ),
        migrations.RenameModel(
            old_name='SmartqQuestionnaireQuestion',
            new_name='TopicCheckingQuestionnaireQuestion',
        ),
        migrations.RenameModel(
            old_name='TopicSmartqSettings',
            new_name='TopicCheckingSettings',
        ),
    ]
