# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20170322_1054'),
        ('topics', '0006_auto_20170319_1524'),
    ]

    operations = [
    ]
