# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_auto_20170322_1721'),
        ('topics', '0008_merge_20170322_1845'),
    ]

    operations = [
    ]
