# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_merge_20170323_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='filltopicsquestionnaireentrancestep',
            name='text_questionnaire_is_on_checking_questions',
            field=models.TextField(blank=True, help_text='Текст, который показывается, когда пользователь не ответил на проверочные вопросы. Поддерживается Markdown'),
        ),
    ]
