# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0012_topiccheckingquestionnaire_checked_at'),
        ('topics', '0011_auto_20170324_1143'),
    ]

    operations = [
    ]
