# Generated by Django 2.0.3 on 2018-03-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0014_auto_20180217_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filltopicsquestionnaireentrancestep',
            options={'base_manager_name': 'objects'},
        ),
    ]
