# Generated by Django 2.0.3 on 2018-04-21 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0074_auto_20180418_1822'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0016_auto_20180331_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsEntranceLevelLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.EntranceLevel', verbose_name='уровень')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_level_limits', to='topics.TopicQuestionnaire', verbose_name='тематическая анкета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'topics entrance level limits',
                'verbose_name': 'topics entrance level limit',
            },
        ),
        migrations.AlterUniqueTogether(
            name='topicsentrancelevellimit',
            unique_together={('questionnaire', 'user')},
        ),
    ]
