# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(help_text='По-умолчанию устанавливается в текущее системное время. Используется только для отладки, так как сгенерированные для вопроса данные целиком храняться в базе.', max_length=100)),
                ('data_json', models.TextField()),
                ('answer_json', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text="Используется в url'ах. Например, build-heap.", max_length=100, unique=True)),
                ('template_html', models.TextField(help_text='Jinja2 шаблон для HTML кода вопроса.')),
                ('template_css', models.TextField(blank=True, default='', help_text='Jinja2 шаблон для CSS кода вопроса.')),
                ('template_js', models.TextField(blank=True, default='', help_text='Jinja2 шаблон для Javascript кода вопроса.')),
                ('code', models.TextField(help_text='Код python модуля, в котором должны быть определены классы Generator и Checker. В модуле изначально доступен модуль api. Generator и Checker должны быть отнаследованы от api.Generator и api.Checker соответственно.')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffGeneratedQuestion',
            fields=[
                ('generatedquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smartq.GeneratedQuestion')),
            ],
            bases=('smartq.generatedquestion',),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='base_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartq.Question'),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому выдан этот вопрос. Другие пользователи не смогут на него отвечать.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
