# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='answer_json',
            field=models.TextField(blank=True, help_text='Последний ответ на вопрос, сериализованный в JSON'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='data_json',
            field=models.TextField(help_text='Возвращённый генератором объект, сериализованный в JSON'),
        ),
    ]
