# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0008_auto_20160528_1748'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractHomePageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Блоки показываются в порядке возрастания этого параметра')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_home.abstracthomepageblock_set+', to='contenttypes.ContentType')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_blocks', to='schools.School')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
