# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstracthomepageblock',
            options={'verbose_name': 'home page block'},
        ),
    ]
