# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.apps import apps as global_apps
from django.db import migrations

import sys
import datetime


class Migration(migrations.Migration):
    operations = [
    ]

    dependencies = [
        ('users', '0009_generate_account_emailaddress'),
    ]

    if global_apps.is_installed('django.contrib.sites'):
        dependencies.append(('sites', '0002_alter_domain_unique'))

    if global_apps.is_installed('social_django'):
        dependencies.append(('social_django', '0006_partial'))

    if global_apps.is_installed('allauth.socialaccount'):
        dependencies.append(('socialaccount', '0003_extra_data_default_dict'))
