# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:39
from __future__ import unicode_literals

from datetime import datetime, timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_detect_poldnev_person_for_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.fromtimestamp(0, tz=timezone.utc)),
            preserve_default=False,
        ),
    ]
