# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='citizenship_other',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Другое гражданство'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='в котором находится школа', max_length=100, verbose_name='Населённый пункт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='insurance_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер медицинского полиса'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, default='', help_text='или страна, если не Россия', max_length=100, verbose_name='Субъект РФ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Телеграмм'),
        ),
    ]
