# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170325_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Школа'),
        ),
    ]
