# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170328_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasswordrecovery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_confirmation_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_confirmed',
        ),
        migrations.DeleteModel(
            name='UserPasswordRecovery',
        ),
    ]
