# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20170402_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Телеграм'),
        ),
    ]
