# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 00:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_userprofile_insurance_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Чтобы быстро понимать, для чего этот список предназначен', max_length=120, verbose_name='Название')),
                ('users', models.ManyToManyField(related_name='_userlist_users_+', to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name_plural': 'user lists',
                'verbose_name': 'user list',
            },
        ),
    ]
