# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-25 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='t_shirt_size',
            field=models.IntegerField(blank=True, choices=[(1, 'XS'), (2, 'S'), (3, 'M'), (4, 'L'), (5, 'XL'), (6, 'XXL')], null=True, validators=[djchoices.choices.ChoicesValidator({1: 'XS', 2: 'S', 3: 'M', 4: 'L', 5: 'XL', 6: 'XXL'})], verbose_name='Размер футболки'),
        ),
    ]
