# Generated by Django 2.0.3 on 2018-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userprofile_t_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codeforces_handle',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Хэндл на codeforces.com'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='informatics_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя пользователя на informatics.msk.ru'),
        ),
    ]
