# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0011_auto_20160508_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueelement',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Значение NULL используется для output-only задач', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejudge.ProgrammingLanguage'),
        ),
    ]
