# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejudge', '0013_solutioncheckingresult_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ejudge.SolutionCheckingResult'),
        ),
    ]
