# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-31 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relativefilepathfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100)),
                ('original_file_name', models.TextField()),
                ('file_size', models.PositiveIntegerField()),
                ('file', relativefilepathfield.fields.RelativeFilePathField(path=settings.SISTEMA_MAIL_ATTACHMENTS_DIR, recursive=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('html_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('headers', models.TextField()),
                ('attachments', models.ManyToManyField(to='mail.Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalEmailUser',
            fields=[
                ('emailuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mail.EmailUser')),
                ('display_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('mail.emailuser',),
        ),
        migrations.CreateModel(
            name='SisEmailUser',
            fields=[
                ('emailuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mail.EmailUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('mail.emailuser',),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_mail.emailuser_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='cc_recipients',
            field=models.ManyToManyField(related_name='cc_received_emails', to='mail.EmailUser'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='recipients',
            field=models.ManyToManyField(related_name='received_emails', to='mail.EmailUser'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mail.EmailUser'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='mail.EmailUser'),
        ),
    ]
