# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20160528_1748'),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.CharField(help_text='Например, ivan-ivanov', max_length=100)),
                ('hash', models.CharField(help_text='Добавляется к email-name для идентификации пользователя', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.SisEmailUser')),
                ('sessions', models.ManyToManyField(to='schools.Session')),
            ],
        ),
    ]
