# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_contactlist_contactrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='contact_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mail.ContactList'),
        ),
    ]
