# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_personalemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='owner',
        ),
        migrations.AddField(
            model_name='contactrecord',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mail.SisEmailUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.EmailUser'),
        ),
        migrations.RemoveField(
            model_name='contactrecord',
            name='contact_list',
        ),
        migrations.AlterUniqueTogether(
            name='contactrecord',
            unique_together=set([('person', 'owner')]),
        ),
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
