# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_personalemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.EmailUser'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='mail.Attachment'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='cc_recipients',
            field=models.ManyToManyField(blank=True, related_name='cc_received_emails', to='mail.EmailUser'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='headers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='html_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_emails', to='mail.EmailUser'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mail.EmailUser'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
