# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20160802_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='is_remove',
            field=models.BooleanField(default=False),
        ),
    ]
