# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 11:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations
from django.utils.timezone import utc
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_auto_20160802_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='thumbnail',
            field=relativefilepathfield.fields.RelativeFilePathField(default=datetime.datetime(2016, 8, 7, 11, 44, 18, 774151, tzinfo=utc), path=settings.SISTEMA_ATTACHMENT_PREVIEWS_DIR, recursive=True),
            preserve_default=False,
        ),
    ]
