# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 11:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations
from django.utils.timezone import utc
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_emailmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='thumbnail',
            field=relativefilepathfield.fields.RelativeFilePathField(default='', path=settings.SISTEMA_ATTACHMENT_PREVIEWS_DIR, recursive=True),
            preserve_default=False,
        ),
    ]
