# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_attachment_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='thumbnail',
            new_name='preview',
        ),
    ]
