# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_auto_20160812_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalemailmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='personalemailmessage',
            name='is_removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
