# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0008_auto_20160410_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceexamtasksolution',
            name='ip',
            field=models.CharField(default='', help_text='IP-адрес, с которого было отправлено решение', max_length=50),
        ),
    ]
