# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0016_userincheckinggroup_is_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancerecommendation',
            name='score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
