# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0017_entrancerecommendation_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancerecommendation',
            name='parallel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrance_recommendations', to='school.Parallel'),
        ),
    ]
