# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0018_auto_20160509_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancestatus',
            name='public_comment',
            field=models.TextField(blank=True, help_text='Публичный комментарий. Может быть виден поступающему'),
        ),
        migrations.AlterField(
            model_name='solutionscore',
            name='scored_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solutionscore',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='entrance.EntranceExamTaskSolution'),
        ),
    ]
