# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0020_auto_20160526_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractabsencereason',
            name='private_comment',
            field=models.TextField(blank=True, help_text='Не показывается школьнику'),
        ),
        migrations.AddField(
            model_name='abstractabsencereason',
            name='public_comment',
            field=models.TextField(blank=True, help_text='Показывается школьнику'),
        ),
    ]
