# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0021_auto_20160526_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrancelevel',
            options={'ordering': ('school_id', 'order')},
        ),
        migrations.RenameField(
            model_name='abstractabsencereason',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='abstractabsencereason',
            old_name='for_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='checkingcomment',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='checkingcomment',
            old_name='for_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='checkinggroup',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='entranceexam',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='entrancelevel',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='entrancerecommendation',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='entrancerecommendation',
            old_name='for_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='entrancestatus',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='entrancestatus',
            old_name='for_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='entrancestep',
            old_name='for_school',
            new_name='school',
        ),
        migrations.AlterUniqueTogether(
            name='checkinggroup',
            unique_together=set([('school', 'short_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='entrancestatus',
            unique_together=set([('school', 'user')]),
        ),
    ]
