# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('entrance', '0022_auto_20160725_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReasonHomePageBlock',
            fields=[
                ('abstracthomepageblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.AbstractHomePageBlock')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.abstracthomepageblock',),
        ),
        migrations.CreateModel(
            name='EnrolledStepsHomePageBlock',
            fields=[
                ('abstracthomepageblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.AbstractHomePageBlock')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.abstracthomepageblock',),
        ),
        migrations.CreateModel(
            name='EntranceStatusHomePageBlock',
            fields=[
                ('abstracthomepageblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.AbstractHomePageBlock')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.abstracthomepageblock',),
        ),
        migrations.CreateModel(
            name='EntranceStepsHomePageBlock',
            fields=[
                ('abstracthomepageblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.AbstractHomePageBlock')),
                ('is_past', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.abstracthomepageblock',),
        ),
    ]
