# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0025_auto_20170311_2331_squashed_0030_auto_20170317_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancestatus',
            name='status',
            field=models.IntegerField(choices=[(1, 'Не участвовал в конкурсе'), (2, 'Автоматический отказ'), (3, 'Не прошёл по конкурсу'), (4, 'Поступил'), (5, 'Подал заявку')], validators=[djchoices.choices.ChoicesValidator({1: 'Не участвовал в конкурсе', 2: 'Автоматический отказ', 3: 'Не прошёл по конкурсу', 4: 'Поступил', 5: 'Подал заявку'})]),
        ),
    ]
