# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0026_auto_20170318_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractentrancestep',
            name='available_from_date',
        ),
        migrations.RemoveField(
            model_name='abstractentrancestep',
            name='available_to_date',
        ),
        migrations.AddField(
            model_name='abstractentrancestep',
            name='available_from_time',
            field=models.DateTimeField(blank=True, default=None, help_text='Начиная с какого времени доступен шаг', null=True),
        ),
        migrations.AddField(
            model_name='abstractentrancestep',
            name='available_to_time',
            field=models.DateTimeField(blank=True, default=None, help_text='До какого времени доступен доступен шаг', null=True),
        ),
    ]
