# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0027_auto_20170318_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUserParticipatingEntranceStep',
            fields=[
                ('abstractentrancestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.AbstractEntranceStep')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.abstractentrancestep',),
        ),
    ]
