# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0028_makeuserparticipatingentrancestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancestatus',
            name='is_status_visible',
            field=models.BooleanField(default=False),
        ),
    ]
