# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20170223_2302'),
        ('entrance', '0029_auto_20170318_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractentrancestep',
            name='parallel',
            field=models.ForeignKey(blank=True, default=None, help_text='Шаг будет показывать только зачисленным в эту параллель', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Parallel'),
        ),
        migrations.AddField(
            model_name='abstractentrancestep',
            name='session',
            field=models.ForeignKey(blank=True, default=None, help_text='Шаг будет показывать только зачисленным в эту смену', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Session'),
        ),
        migrations.AddField(
            model_name='abstractentrancestep',
            name='visible_only_for_enrolled',
            field=models.BooleanField(default=False, help_text='Шаг будет виден только зачисленным в школу пользователям'),
        ),
    ]
