# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0030_auto_20170319_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmprofileentrancestep',
            name='text_after_finish_date',
        ),
        migrations.RemoveField(
            model_name='fillquestionnaireentrancestep',
            name='text_after_finish_date',
        ),
        migrations.RemoveField(
            model_name='solveexamentrancestep',
            name='text_after_finish_date',
        ),
        migrations.AddField(
            model_name='confirmprofileentrancestep',
            name='text_after_finish_date_if_not_passed',
            field=models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг не выполнен. Поддерживается Markdown'),
        ),
        migrations.AddField(
            model_name='confirmprofileentrancestep',
            name='text_after_finish_date_if_passed',
            field=models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг выполнен. Поддерживается Markdown'),
        ),
        migrations.AddField(
            model_name='fillquestionnaireentrancestep',
            name='text_after_finish_date_if_not_passed',
            field=models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг не выполнен. Поддерживается Markdown'),
        ),
        migrations.AddField(
            model_name='fillquestionnaireentrancestep',
            name='text_after_finish_date_if_passed',
            field=models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг выполнен. Поддерживается Markdown'),
        ),
        migrations.AddField(
            model_name='solveexamentrancestep',
            name='text_after_finish_date_if_not_passed',
            field=models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг не выполнен. Поддерживается Markdown'),
        ),
        migrations.AddField(
            model_name='solveexamentrancestep',
            name='text_after_finish_date_if_passed',
            field=models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг выполнен. Поддерживается Markdown'),
        ),
        migrations.AlterField(
            model_name='confirmprofileentrancestep',
            name='text_waiting_for_other_step',
            field=models.TextField(blank=True, help_text='Текст, который показывается, когда не пройден один из предыдущих шагов. Поддерживается Markdown'),
        ),
        migrations.AlterField(
            model_name='fillquestionnaireentrancestep',
            name='text_waiting_for_other_step',
            field=models.TextField(blank=True, help_text='Текст, который показывается, когда не пройден один из предыдущих шагов. Поддерживается Markdown'),
        ),
        migrations.AlterField(
            model_name='solveexamentrancestep',
            name='text_waiting_for_other_step',
            field=models.TextField(blank=True, help_text='Текст, который показывается, когда не пройден один из предыдущих шагов. Поддерживается Markdown'),
        ),
    ]
