# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sizefield.models
import sistema.polymorphic


def forwards_func(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for model_name in ['EntranceExamTask',
                       'EntranceExamTaskSolution',
                       'EntranceLevelUpgradeRequirement']:
        model = apps.get_model('entrance', model_name)
        children = sistema.polymorphic.get_all_inheritors(model)
        for child in children:
            for obj in child.objects.all():
                content_type = ContentType.objects.db_manager().get_for_model(
                    obj,
                    for_concrete_model=False
                )
                obj.polymorphic_ctype = content_type
                obj.save()

    EntranceExamTaskSolution = apps.get_model('entrance',
                                              'EntranceExamTaskSolution')
    TestEntranceExamTaskSolution = apps.get_model('entrance',
                                                  'TestEntranceExamTaskSolution')
    new_ct = ContentType.objects.get_for_model(TestEntranceExamTaskSolution)
    EntranceExamTaskSolution.objects.filter(
        polymorphic_ctype__isnull=True
    ).update(polymorphic_ctype=new_ct)


def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entrance', '0031_auto_20170322_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEntranceExamTaskSolution',
            fields=[
                ('entranceexamtasksolution_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True, primary_key=True,
                                      serialize=False,
                                      to='entrance.EntranceExamTaskSolution')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.entranceexamtasksolution',),
        ),
        migrations.AddField(
            model_name='entranceexamtask',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_entrance.entranceexamtask_set+',
                                    to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='entranceexamtasksolution',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_entrance.entranceexamtasksolution_set+',
                                    to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='entrancelevelupgraderequirement',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='polymorphic_entrance.entrancelevelupgraderequirement_set+',
                                    to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='entranceexamtasksolution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='solutions',
                                    to='entrance.EntranceExamTask'),
        ),
        migrations.AlterField(
            model_name='entranceexamtasksolution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='entrance_exam_solutions',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programentranceexamtask',
            name='memory_limit',
            field=sizefield.models.FileSizeField(),
        ),
        migrations.AlterField(
            model_name='programentranceexamtask',
            name='time_limit',
            field=models.PositiveIntegerField(help_text='В миллисекундах'),
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
