# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0032_auto_20170324_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceexamtask',
            name='custom_description',
            field=models.TextField(blank=True, help_text='Текст с описанием типа задачи. Оставьте пустым, тогда будет использован текст по умолчанию для данного вида задач. В этом тексте можно указать, например, для кого эта задача предназначена.\nПоддерживается Markdown'),
        ),
    ]
