# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0033_entranceexamtask_custom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='programentranceexamtask',
            name='problem_type',
            field=models.PositiveIntegerField(choices=[(0, 'Стандартная задача'), (1, 'Задача на сдачу файла с ответом, а не программы')], default=0, help_text='Тип задачи', validators=[djchoices.choices.ChoicesValidator({0: 'Стандартная задача', 1: 'Задача на сдачу файла, а не программы'})]),
        ),
        migrations.AlterField(
            model_name='programentranceexamtasksolution',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Значение NULL исользуется для output-only задач', null=True, on_delete=django.db.models.deletion.CASCADE, to='ejudge.ProgrammingLanguage'),
        ),
    ]
