# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('entrance', '0034_auto_20170405_1555'), ('entrance', '0035_auto_20170406_0117')]

    dependencies = [
        ('entrance', '0033_entranceexamtask_custom_description'),
        ('ejudge', '0012_auto_20170405_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputOnlyEntranceExamTask',
            fields=[
                ('entranceexamtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.EntranceExamTask')),
                ('ejudge_contest_id', models.PositiveIntegerField(help_text='ID контеста в еджадже')),
                ('ejudge_problem_id', models.PositiveIntegerField(help_text='ID задачи в еджадже')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.entranceexamtask',),
        ),
        migrations.CreateModel(
            name='OutputOnlyEntranceExamTaskSolution',
            fields=[
                ('entranceexamtasksolution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.EntranceExamTaskSolution')),
                ('ejudge_queue_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejudge.QueueElement')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.entranceexamtasksolution',),
        ),
        migrations.AlterField(
            model_name='programentranceexamtasksolution',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejudge.ProgrammingLanguage'),
        ),
    ]
