# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0014_auto_20170223_2302'),
        ('entrance', '0034_auto_20170405_1555_squashed_0035_auto_20170406_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceLevelOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='entrance.EntranceLevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_level_overrides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entranceleveloverride',
            unique_together=set([('school', 'user')]),
        ),
    ]
