# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0034_auto_20170405_1555_squashed_0035_auto_20170406_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractabsencereason',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_reasons', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='abstractabsencereason',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_reasons', to=settings.AUTH_USER_MODEL),
        ),
    ]
