# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrance', '0034_auto_20170405_1555_squashed_0035_auto_20170406_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, help_text='Произвольный комментарий проверяюшего')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='entrance.EntranceExamTaskSolution')),
            ],
        ),
        migrations.RemoveField(
            model_name='entrancerecommendation',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='entrancerecommendation',
            name='parallel',
        ),
        migrations.RemoveField(
            model_name='entrancerecommendation',
            name='school',
        ),
        migrations.RemoveField(
            model_name='entrancerecommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='solutionscore',
            name='scored_by',
        ),
        migrations.RemoveField(
            model_name='solutionscore',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='checkinglock',
            name='locked_user',
        ),
        migrations.AddField(
            model_name='checkinggroup',
            name='tasks',
            field=models.ManyToManyField(related_name='_checkinggroup_tasks_+', to='entrance.FileEntranceExamTask'),
        ),
        migrations.AddField(
            model_name='checkinglock',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.EntranceExamTask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkinglock',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entrance_checking_locks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkingcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_checking_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkinggroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_checking_groups', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='checkinglock',
            name='locked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_checking_locks_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userincheckinggroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='entrance.CheckingGroup'),
        ),
        migrations.AlterField(
            model_name='userincheckinggroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EntranceRecommendation',
        ),
        migrations.DeleteModel(
            name='SolutionScore',
        ),
    ]
