# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0035_auto_20170417_1806'),
        ('entrance', '0035_auto_20170414_0919'),
    ]

    operations = [
    ]
