# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modules.entrance.models.checking


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0035_auto_20170425_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userincheckinggroup',
            options={},
        ),
        migrations.AlterField(
            model_name='checkingcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='checkinglock',
            name='locked_until',
            field=models.DateTimeField(db_index=True, default=modules.entrance.models.checking.get_locked_timeout),
        ),
        migrations.AlterField(
            model_name='entranceexamtasksolution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userincheckinggroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userincheckinggroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_time_users', to='entrance.CheckingGroup'),
        ),
        migrations.AlterField(
            model_name='userincheckinggroup',
            name='is_actual',
            field=models.BooleanField(default=True, help_text='True для актуальных записей, False для исторических'),
        ),
    ]
