# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0036_auto_20170426_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedsolution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
