# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0038_merge_20170427_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentranceexamtask',
            name='checking_criteria',
            field=models.TextField(blank=True, default='', help_text='Критерии выставления баллов для проверяющих. Поддерживается Markdown'),
        ),
        migrations.AlterField(
            model_name='checkinggroup',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='_checkinggroup_tasks_+', to='entrance.FileEntranceExamTask'),
        ),
    ]
