# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entrance', '0039_auto_20170429_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceUserMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParallelScoreEntranceUserMetricFileTaskEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.FileEntranceExamTask')),
            ],
        ),
        migrations.CreateModel(
            name='ParallelScoreEntranceUserMetricProgramTaskEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.ProgramEntranceExamTask')),
            ],
        ),
        migrations.CreateModel(
            name='ParallelScoreEntranceUserMetric',
            fields=[
                ('entranceusermetric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.EntranceUserMetric')),
                ('max_theory_score', models.IntegerField(blank=True, null=True)),
                ('replacing_program_tasks', models.ManyToManyField(related_name='_parallelscoreentranceusermetric_replacing_program_tasks_+', to='entrance.ProgramEntranceExamTask')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.entranceusermetric',),
        ),
        migrations.AddField(
            model_name='entranceusermetric',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='entrance.EntranceExam'),
        ),
        migrations.AddField(
            model_name='entranceusermetric',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_entrance.entranceusermetric_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='parallelscoreentranceusermetricprogramtaskentry',
            name='parallel_score_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_task_entries', to='entrance.ParallelScoreEntranceUserMetric'),
        ),
        migrations.AddField(
            model_name='parallelscoreentranceusermetricfiletaskentry',
            name='parallel_score_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_task_entries', to='entrance.ParallelScoreEntranceUserMetric'),
        ),
        migrations.AlterUniqueTogether(
            name='entranceusermetric',
            unique_together=set([('name', 'exam')]),
        ),
    ]
