# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0039_auto_20170429_1535'),
        ('entrance', '0035_auto_20170417_1806'),
    ]

    operations = [
    ]
