# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0040_merge_20170430_1504'),
        ('entrance', '0040_auto_20170507_1304'),
    ]

    operations = [
    ]
