# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0041_merge_20170509_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parallelscoreentranceusermetricfiletaskentry',
            options={'verbose_name': 'Балл за теорию', 'verbose_name_plural': 'Баллы за теорию'},
        ),
        migrations.AlterModelOptions(
            name='parallelscoreentranceusermetricprogramtaskentry',
            options={'verbose_name': 'Балл за практику', 'verbose_name_plural': 'Баллы за практику'},
        ),
        migrations.RenameField(
            model_name='parallelscoreentranceusermetric',
            old_name='max_theory_score',
            new_name='max_possible_theory_score',
        ),
        migrations.AlterField(
            model_name='parallelscoreentranceusermetric',
            name='replacing_program_tasks',
            field=models.ManyToManyField(blank=True, related_name='_parallelscoreentranceusermetric_replacing_program_tasks_+', to='entrance.ProgramEntranceExamTask'),
        ),
    ]
