# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0042_auto_20170509_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parallelscoreentranceusermetricfiletaskentry',
            options={'verbose_name': 'балл за теорию', 'verbose_name_plural': 'баллы за теорию'},
        ),
        migrations.AlterModelOptions(
            name='parallelscoreentranceusermetricprogramtaskentry',
            options={'verbose_name': 'балл за практику', 'verbose_name_plural': 'баллы за практику'},
        ),
        migrations.AddField(
            model_name='parallelscoreentranceusermetric',
            name='max_possible_practice_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
