# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0043_auto_20170510_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancelevel',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='entrance_levels', to='entrance.EntranceExamTask'),
        ),
    ]
