# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0046_auto_20170515_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractabsencereason',
            options={'verbose_name': 'Absence reason'},
        ),
        migrations.AlterModelOptions(
            name='abstractentrancestep',
            options={'verbose_name': 'Entrance step'},
        ),
    ]
