# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20170617_1842'),
        ('entrance', '0047_auto_20170515_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaticipatedInSchoolEntranceStep',
            fields=[
                ('abstractentrancestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.AbstractEntranceStep')),
                ('text_before_start_date', models.TextField(blank=True, help_text='Текст, который показывается до даты начала заполнения шага. Поддерживается Markdown')),
                ('text_after_finish_date_if_passed', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг выполнен. Поддерживается Markdown')),
                ('text_after_finish_date_if_not_passed', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг не выполнен. Поддерживается Markdown')),
                ('text_waiting_for_other_step', models.TextField(blank=True, help_text='Текст, который показывается, когда не пройден один из предыдущих шагов. Поддерживается Markdown')),
                ('text_step_is_not_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг ещё не пройден. Поддерживается Markdown')),
                ('text_step_is_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг пройден пользователем. Поддерживается Markdown')),
                ('school_to_check_participation', models.ForeignKey(help_text='Шаг будет считаться пройденным только если пользователь принимал участие в этой школе', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.abstractentrancestep', models.Model),
        ),
    ]
