# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0048_userpaticipatedinschoolentrancestep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPaticipatedInSchoolEntranceStep',
            new_name='UserParticipatedInSchoolEntranceStep',
        ),
    ]
