# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    # Django 2.0 requires this for renaming models in SQLite
    # https://stackoverflow.com/questions/48549068/django-db-utils-notsupportederror-in-sqlite-why-not-supported-in-sqlite
    atomic = False

    dependencies = [
        ('entrance', '0048_userpaticipatedinschoolentrancestep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPaticipatedInSchoolEntranceStep',
            new_name='UserParticipatedInSchoolEntranceStep',
        ),
    ]
