# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0049_auto_20171003_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceexam',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_exam', to='schools.School'),
        ),
    ]
