# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-25 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrance', '0050_auto_20171019_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParticipatedInSchoolEntranceStepException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.ForeignKey(help_text='Шаг, для которого предназначено данное исключение', on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='entrance.UserParticipatedInSchoolEntranceStep')),
                ('user', models.ForeignKey(help_text='Пользователь, для которого шаг считается выполненным, даже если он не участвовал в соответствующей школе', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
