# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 00:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0054_use_dates_app_3_20171115_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractentrancestep',
            options={'verbose_name': 'entrance step'},
        ),
        migrations.AlterField(
            model_name='entrancestatus',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programentranceexamtasksolution',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ejudge.ProgrammingLanguage'),
        ),
    ]
