# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0056_merge_20180302_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancestatusgroup',
            name='status',
            field=models.IntegerField(choices=[(1, 'Не участвовал в конкурсе'), (2, 'Автоматический отказ'), (3, 'Не прошёл по конкурсу'), (4, 'Поступил'), (5, 'Подал заявку'), (6, 'В резервном списке')], validators=[djchoices.choices.ChoicesValidator({1: 'Не участвовал в конкурсе', 2: 'Автоматический отказ', 3: 'Не прошёл по конкурсу', 4: 'Поступил', 5: 'Подал заявку', 6: 'В резервном списке'})]),
        ),
    ]
