# Generated by Django 2.0.3 on 2018-03-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0058_markdownentrancestep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmprofileentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='ensureprofileisfullentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='entranceexamtask',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='entrancelevelupgraderequirement',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='entrancestatusgroup',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='entrancestepshomepageblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fileentranceexamtask',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fileentranceexamtasksolution',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fillquestionnaireentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='makeuserparticipatingentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='markdownentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='notconfirmedabsencereason',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='parallelscoreentranceusermetric',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='rejectionabsencereason',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='resultsentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='solveexamentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='solvetaskentrancelevelupgraderequirement',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='testentranceexamtask',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='testentranceexamtasksolution',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='userparticipatedinschoolentrancestep',
            options={'base_manager_name': 'objects'},
        ),
    ]
