# Generated by Django 2.0.3 on 2018-04-06 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrance', '0059_auto_20180312_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Например, «По вступительной работе». Поддерживается Markdown')),
                ('need_moderation', models.BooleanField(help_text='Нужна ли модерация, если пользователь выбрал этот тип поступления')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedEnrollmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moderated', models.BooleanField(help_text='Обработан ли запрос')),
                ('is_approved', models.BooleanField(help_text='Одобрен ли запрос')),
                ('enrollment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='entrance.EnrollmentType')),
                ('entrance_level', models.ForeignKey(blank=True, default=None, help_text='Выставленный уровень вступительной', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.EntranceLevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectEnrollmentTypeEntranceStep',
            fields=[
                ('abstractentrancestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.AbstractEntranceStep')),
                ('text_before_start_date', models.TextField(blank=True, help_text='Текст, который показывается до даты начала заполнения шага. Поддерживается Markdown')),
                ('text_after_finish_date_if_passed', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг выполнен. Поддерживается Markdown')),
                ('text_after_finish_date_if_not_passed', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг не выполнен. Поддерживается Markdown')),
                ('text_waiting_for_other_step', models.TextField(blank=True, help_text='Текст, который показывается, когда не пройден один из предыдущих шагов. Поддерживается Markdown')),
                ('text_step_is_not_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг ещё не пройден. Поддерживается Markdown')),
                ('text_step_is_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг пройден пользователем. Поддерживается Markdown')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('entrance.abstractentrancestep', models.Model),
        ),
        migrations.AddField(
            model_name='enrollmenttype',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='entrance.SelectEnrollmentTypeEntranceStep'),
        ),
    ]
