# Generated by Django 2.0.3 on 2018-04-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrance', '0060_auto_20180406_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedenrollmenttype',
            name='step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.SelectEnrollmentTypeEntranceStep'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollmenttype',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_types', to='entrance.SelectEnrollmentTypeEntranceStep'),
        ),
        migrations.AlterUniqueTogether(
            name='selectedenrollmenttype',
            unique_together={('user', 'step')},
        ),
    ]
