# Generated by Django 2.0.3 on 2018-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0061_auto_20180406_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmenttype',
            name='text',
            field=models.TextField(help_text='Например, «По вступительной работе»'),
        ),
    ]
