# Generated by Django 2.0.3 on 2018-04-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0062_auto_20180406_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectenrollmenttypeentrancestep',
            name='text_on_moderation',
            field=models.TextField(default='', help_text='Текст, который показывается пользователю, пока выбранный вариант находится на модерации. Поддерживается Markdown'),
            preserve_default=False,
        ),
    ]
