# Generated by Django 2.0.3 on 2018-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0063_selectenrollmenttypeentrancestep_text_on_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedenrollmenttype',
            name='is_approved',
            field=models.BooleanField(db_index=True, help_text='Одобрен ли запрос'),
        ),
        migrations.AlterField(
            model_name='selectedenrollmenttype',
            name='is_moderated',
            field=models.BooleanField(db_index=True, help_text='Обработан ли запрос'),
        ),
    ]
