# Generated by Django 2.0.3 on 2018-04-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0064_auto_20180406_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectenrollmenttypeentrancestep',
            name='text_failed_moderation',
            field=models.TextField(default='', help_text='Текст, который показывается пользователю, когда выбранный вариант не прошёл модерацию. Поддерживается Markdown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectenrollmenttypeentrancestep',
            name='text_passed_moderation',
            field=models.TextField(default='', help_text='Текст, который показывается пользователю, когда выбранный вариант прошёл модерацию. Поддерживается Markdown'),
            preserve_default=False,
        ),
    ]
