# Generated by Django 2.0.3 on 2018-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0065_auto_20180407_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmenttype',
            old_name='need_moderation',
            new_name='needs_moderation',
        ),
        migrations.AddField(
            model_name='selectedenrollmenttype',
            name='custom_resolution_text',
            field=models.TextField(blank=True, help_text='Текст, объясняющий решение организаторов. Можно не указывать, тогда школьнику покажется текст по умолчанию в зависимости от того, одобрена ли заявка. Поддерживается Markdown'),
        ),
        migrations.AlterField(
            model_name='selectedenrollmenttype',
            name='is_approved',
            field=models.BooleanField(db_index=True, help_text='Одобрена ли заявка'),
        ),
        migrations.AlterField(
            model_name='selectedenrollmenttype',
            name='is_moderated',
            field=models.BooleanField(db_index=True, help_text='Обработана ли заявка'),
        ),
    ]
