# Generated by Django 2.0.3 on 2018-04-06 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0066_auto_20180407_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceExamTaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.SlugField(help_text='Может состоять только из букв, цифр, знака подчеркивания и дефиса.')),
                ('title', models.CharField(help_text='Заголовок категории, например «Практические задачи:»', max_length=100, verbose_name='заголовок')),
                ('order', models.IntegerField(help_text='Категории задач отображаются в заданном порядке', verbose_name='порядок')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to='entrance.EntranceExam', verbose_name='экзамен')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entranceexamtaskcategory',
            unique_together={('exam', 'order'), ('exam', 'short_name')},
        ),
    ]
