# Generated by Django 2.0.3 on 2018-04-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0067_4_make_categories_mandatory_20180406_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entranceexamtaskcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
