# Generated by Django 2.0.3 on 2018-04-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20180407_1742'),
        ('entrance', '0068_auto_20180406_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedenrollmenttype',
            name='parallel',
            field=models.ForeignKey(blank=True, help_text='Параллель, в которую школьник зачислен без выполнения вступительной', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Parallel', verbose_name='параллель'),
        ),
        migrations.AlterField(
            model_name='selectedenrollmenttype',
            name='entrance_level',
            field=models.ForeignKey(blank=True, default=None, help_text='Выставленный уровень вступительной. Должен содержать задачи, необходимые для поступления в следующую параллель после той, в которую школьник зачислен автоматически.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.EntranceLevel', verbose_name='уровень вступительной'),
        ),
    ]
