# Generated by Django 2.0.3 on 2018-04-09 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0070_auto_20180409_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedenrollmenttype',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Когда заявка была рассмотрена', null=True, verbose_name='время модерации'),
        ),
        migrations.AlterField(
            model_name='selectedenrollmenttype',
            name='reviewed_by',
            field=models.ForeignKey(help_text='Пользователь, который одобрил или отклонил заявку', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
    ]
