# Generated by Django 2.0.3 on 2018-04-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0072_selectenrollmenttypeentrancestep_review_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='entranceexamtaskcategory',
            name='is_mandatory',
            field=models.BooleanField(default=True, help_text='Обязательно ли решать задачи в этой категории, чтобы вступительная считалась выполненной?', verbose_name='обязательная категория'),
        ),
    ]
