# Generated by Django 2.0.3 on 2018-04-20 13:18
from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunPython


def migrate_checking_groups(apps, schema_editor):
    CheckingGroup = apps.get_model('entrance', 'CheckingGroup')
    UserInCheckingGroup = apps.get_model('entrance', 'UserInCheckingGroup')
    ManuallyFilledGroup = apps.get_model('groups', 'ManuallyFilledGroup')
    UserInGroupMembership = apps.get_model('groups', 'UserInGroupMembership')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for checking_group in CheckingGroup.objects.all():
        checking_group.group = ManuallyFilledGroup.objects.create(
            school=checking_group.school,
            short_name=checking_group.short_name,
            name=checking_group.name,
            description='Группа проверки %s для %s' % (
                checking_group.name,
                checking_group.school.name
            )
        )
        checking_group.save()

    content_type = ContentType.objects.get_for_model(ManuallyFilledGroup)
    (ManuallyFilledGroup.objects
        .filter(polymorphic_ctype__isnull=True)
        .update(polymorphic_ctype=content_type))

    for user_in_group in UserInCheckingGroup.objects.all():
        if not user_in_group.is_actual:
            continue

        manually_filled_group = user_in_group.group.group.manuallyfilledgroup
        UserInGroupMembership.objects.create(
            group=manually_filled_group,
            member=user_in_group.user,
            added_by=None  # added by sistema
        )


def reverse_migrate_checking_groups(apps, schema_editor):
    CheckingGroup = apps.get_model('entrance', 'CheckingGroup')
    UserInCheckingGroup = apps.get_model('entrance', 'UserInCheckingGroup')
    UserInGroupMembership = apps.get_model('groups', 'UserInGroupMembership')

    for checking_group in CheckingGroup.objects.all():
        user_ids = UserInGroupMembership.objects.filter(
            group=checking_group.group
        ).values_list('member_id', flat=True)
        for user_id in user_ids:
            UserInCheckingGroup.objects.create(
                group=checking_group,
                user_id=user_id
            )
        checking_group.group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('entrance', '0074_auto_20180418_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinggroup',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup', null=True),
            preserve_default=False,
        ),
        RunPython(migrate_checking_groups, reverse_migrate_checking_groups),
        migrations.AlterField(
            model_name='checkinggroup',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup'),
        )
    ]
