# Generated by Django 2.0.3 on 2018-04-20 13:18
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('entrance', '0074_auto_20180418_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinggroup',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup', null=True),
            preserve_default=False,
        ),
    ]
