# Generated by Django 2.0.3 on 2018-04-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0076_migrate_checking_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userincheckinggroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userincheckinggroup',
            name='user',
        ),
        migrations.AlterField(
            model_name='checkinggroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup'),
        ),
        migrations.DeleteModel(
            name='UserInCheckingGroup',
        ),
    ]
