# Generated by Django 2.0.3 on 2018-05-19 12:22

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunPython


def extract_sessions_and_parallels_forward(apps, schema_editor):
    EntranceStatus = apps.get_model('entrance', 'EntranceStatus')
    EnrolledToSessionAndParallel = apps.get_model('entrance', 'EnrolledToSessionAndParallel')
    for status in EntranceStatus.objects.all():
        if status.session is None and status.parallel is None:
            continue

        EnrolledToSessionAndParallel.objects.create(
            entrance_status=status,
            session=status.session,
            parallel=status.parallel,
        )


def extract_sessions_and_parallels_backward(apps, schema_editor):
    EnrolledToSessionAndParallel = apps.get_model('entrance', 'EnrolledToSessionAndParallel')
    for session_and_parallel in EnrolledToSessionAndParallel.objects.all():
        status = session_and_parallel.entrance_status
        status.session = session_and_parallel.session
        status.parallel = session_and_parallel.parallel
        status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20180407_1742'),
        ('entrance', '0077_auto_20180421_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledToSessionAndParallel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_and_parallels', to='entrance.EntranceStatus')),
                ('parallel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Parallel')),
                ('session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Session')),
            ],
        ),
        RunPython(
            extract_sessions_and_parallels_forward,
            extract_sessions_and_parallels_backward
        )
    ]
