# Generated by Django 2.0.3 on 2018-05-19 12:22

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunPython


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20180407_1742'),
        ('entrance', '0077_auto_20180421_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledToSessionAndParallel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_and_parallels', to='entrance.EntranceStatus')),
                ('parallel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Parallel')),
                ('session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Session')),
            ],
        ),
    ]
