# Generated by Django 2.0.3 on 2018-05-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0078_enrolledtosessionandparallel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrancestatus',
            name='parallel',
        ),
        migrations.RemoveField(
            model_name='entrancestatus',
            name='session',
        ),
    ]
