# Generated by Django 2.0.3 on 2018-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0079_auto_20180519_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledtosessionandparallel',
            name='selected_by_user',
            field=models.BooleanField(default=False, help_text='Пользователь может выбрать одну из предложенных ему параллелей и смен'),
        ),
    ]
