# Generated by Django 2.0.3 on 2018-05-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('schools', '0018_auto_20180407_1742'),
        ('entrance', '0079_auto_20180519_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApprovingStatusGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('is_approved', models.BooleanField(help_text='Поместить в группу тех, кто подтвердил участие, или тех, кто не подтвердил? Отказавшиеся от участия в любом случае не попадают в группу')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
        migrations.RemoveField(
            model_name='entrancestatus',
            name='parallel',
        ),
        migrations.RemoveField(
            model_name='entrancestatus',
            name='session',
        ),
        migrations.AddField(
            model_name='enrolledtosessionandparallel',
            name='selected_by_user',
            field=models.BooleanField(db_index=True, default=False, help_text='Пользователь может выбрать одну из предложенных ему параллелей и смен'),
        ),
        migrations.AddField(
            model_name='entrancestatus',
            name='approved_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='entrancestatus',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Подтверждено ли участие пользователем. Имеет смысл, только если статус = «Поступил»'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledtosessionandparallel',
            unique_together={('entrance_status', 'session', 'parallel')},
        ),
    ]
