# Generated by Django 2.0.3 on 2018-05-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('schools', '0018_auto_20180407_1742'),
        ('entrance', '0080_auto_20180520_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledUsersGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('parallel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Parallel')),
                ('session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Session')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
    ]
