# Generated by Django 2.0.3 on 2018-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20180407_1742'),
        ('entrance', '0080_enrolledtosessionandparallel_selected_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledtosessionandparallel',
            name='selected_by_user',
            field=models.BooleanField(db_index=True, default=False, help_text='Пользователь может выбрать одну из предложенных ему параллелей и смен'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledtosessionandparallel',
            unique_together={('entrance_status', 'session', 'parallel')},
        ),
    ]
