# Generated by Django 2.0.3 on 2018-10-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_auto_20180407_1742'),
        ('groups', '0004_auto_20180312_2139'),
        ('entrance', '0081_enrolledusersgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIsMemberOfGroupEntranceStep',
            fields=[
                ('abstractentrancestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.AbstractEntranceStep')),
                ('text_before_start_date', models.TextField(blank=True, help_text='Текст, который показывается до даты начала заполнения шага. Поддерживается Markdown')),
                ('text_after_finish_date_if_passed', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг выполнен. Поддерживается Markdown')),
                ('text_after_finish_date_if_not_passed', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг не выполнен. Поддерживается Markdown')),
                ('text_waiting_for_other_step', models.TextField(blank=True, help_text='Текст, который показывается, когда не пройден один из предыдущих шагов. Поддерживается Markdown')),
                ('text_step_is_not_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг ещё не пройден. Поддерживается Markdown')),
                ('text_step_is_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг пройден пользователем. Поддерживается Markdown')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('entrance.abstractentrancestep', models.Model),
        ),
        migrations.CreateModel(
            name='UsersParticipatedInSchoolGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('school_to_check_participation', models.ForeignKey(help_text='В группу автоматически попадут все пользователи, принимавшие участие в этой школе', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.School')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
        migrations.AddField(
            model_name='userismemberofgroupentrancestep',
            name='group',
            field=models.ForeignKey(help_text='Шаг будет считаться пройденным только если пользователь состоит в группе', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup'),
        ),
    ]
