# Generated by Django 2.0.3 on 2018-05-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0081_auto_20180520_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancestatus',
            name='approved_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='entrancestatus',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Подтверждено ли участие пользователем. Имеет смысл, только если статус = «Поступил»'),
        ),
    ]
