# Generated by Django 2.0.3 on 2018-10-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0082_auto_20181024_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userismemberofgroupentrancestep',
            name='group',
            field=models.ForeignKey(help_text='Шаг будет считаться пройденным только если пользователь состоит в группе. Пройденный шаг невидим.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='groups.AbstractGroup'),
        ),
    ]
