# Generated by Django 2.0.3 on 2018-05-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('entrance', '0082_auto_20180520_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentApprovingStatusGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('is_approved', models.BooleanField(help_text='Поместить в группу тех, кто подтвердил участие, или тех, кто не подтвердил? Отказавщиеся от участия в любом случае не попадают в группу')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
    ]
