# Generated by Django 2.0.3 on 2019-04-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20180312_2139'),
        ('entrance', '0083_auto_20181025_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedEnrollmentTypeGroup',
            fields=[
                ('abstractgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groups.AbstractGroup')),
                ('only_approved', models.BooleanField(default=True, help_text='Добавлять в группу только тех, кому одобрили (автоматически или вручную) этот способ поступления')),
                ('enrollment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entrance.EnrollmentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('groups.abstractgroup',),
        ),
    ]
