# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20160527_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='finish_date',
            field=models.DateField(default=datetime.date(2016, 5, 28), help_text='Последний день смены'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 5, 28), help_text='Первый день смены'),
            preserve_default=False,
        ),
    ]
