# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('abstractdocumentblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='generator.AbstractDocumentBlock')),
                ('filename', relativefilepathfield.fields.RelativeFilePathField(path=settings.SISTEMA_GENERATOR_ASSETS_DIR, recursive=True)),
                ('width', models.PositiveIntegerField(blank=True, default=None, help_text='В пунктах. Оставьте пустым, чтобы взять размеры самой картинки', null=True)),
                ('height', models.PositiveIntegerField(blank=True, default=None, help_text='В пунктах. Оставьте пустым, чтобы взять размеры самой картинки', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('generator.abstractdocumentblock',),
        ),
    ]
