# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20160531_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetablestylecommand',
            name='command_name',
            field=models.CharField(choices=[('LINEBEFORE', 'Linebefore'), ('BOX', 'Box'), ('LINEABOVE', 'Lineabove'), ('OUTLINE', 'Outline'), ('GRID', 'Grid'), ('LINEAFTER', 'Lineafter'), ('LINEBELOW', 'Linebelow'), ('INNERGRID', 'Innergrid')], max_length=100),
        ),
    ]
