# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20160802_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetablestylecommand',
            name='command_name',
            field=models.CharField(choices=[('LINEAFTER', 'Lineafter'), ('INNERGRID', 'Innergrid'), ('LINEABOVE', 'Lineabove'), ('GRID', 'Grid'), ('LINEBELOW', 'Linebelow'), ('BOX', 'Box'), ('OUTLINE', 'Outline'), ('LINEBEFORE', 'Linebefore')], max_length=100),
        ),
    ]
