# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20160810_1134'),
        ('generator', '0004_auto_20160731_0841'),
    ]

    operations = [
    ]
