# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20170618_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetablestylecommand',
            name='command_name',
            field=models.CharField(choices=[('BOX', 'Box'), ('GRID', 'Grid'), ('INNERGRID', 'Innergrid'), ('LINEABOVE', 'Lineabove'), ('LINEAFTER', 'Lineafter'), ('LINEBEFORE', 'Linebefore'), ('LINEBELOW', 'Linebelow'), ('OUTLINE', 'Outline')], max_length=100),
        ),
    ]
