# Generated by Django 2.0.3 on 2018-03-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20180309_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alignmenttablestylecommand',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='cellformattingtablestylecommand',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fonttablestylecommand',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='leadingtablestylecommand',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='linetablestylecommand',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paddingtablestylecommand',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='pagebreak',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='spacer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='textcolortablestylecommand',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='valigntablestylecommand',
            options={'base_manager_name': 'objects'},
        ),
    ]
