# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20180217_0000'),
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydate',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Школа, к которой относится эта дата. Поле может быть пустым, если дата не относится ни к какой школе.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_dates', to='schools.School'),
        ),
    ]
