# Generated by Django 2.0.3 on 2018-03-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_assign_school_to_key_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='keydate',
            name='short_name',
            field=models.SlugField(default='', help_text='Может состоять только из букв, цифр, знака подчеркивания и дефиса.'),
            preserve_default=False,
        ),
    ]
