# Generated by Django 2.0.3 on 2018-03-23 21:15

from django.db import migrations


def populate_short_names(apps, schema):
    key_date_class = apps.get_model('dates', 'KeyDate')
    for key_date in key_date_class.objects.all():
        key_date.short_name = 'key-date-' + str(key_date.pk)
        key_date.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_1_add_short_name_20180323_2115'),
    ]

    operations = [
        migrations.RunPython(populate_short_names, migrations.RunPython.noop),
    ]
