# Generated by Django 2.0.3 on 2018-03-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_2_populate_short_names_20180323_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keydate',
            unique_together={('school', 'short_name')},
        ),
    ]
