# Generated by Django 2.0.3 on 2018-05-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0006_auto_20180510_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkeydateexception',
            options={'verbose_name': 'user key date exception', 'verbose_name_plural': 'user key date exceptions'},
        ),
    ]
