# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled_scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolledscanrequirement',
            unique_together=set([('for_school', 'short_name')]),
        ),
    ]
