# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled_scans', '0002_auto_20160515_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledscan',
            name='original_filename',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
