# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled_scans', '0004_auto_20160601_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledscan',
            old_name='for_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='enrolledscanrequirement',
            old_name='for_school',
            new_name='school',
        ),
        migrations.AlterUniqueTogether(
            name='enrolledscanrequirement',
            unique_together=set([('school', 'short_name')]),
        ),
    ]
