# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled_scans', '0005_auto_20160725_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledscan',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='enrolled_scans.EnrolledScanRequirement'),
        ),
        migrations.AlterField(
            model_name='enrolledscanrequirement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_scan_requirements', to='schools.School'),
        ),
    ]
