# Generated by Django 2.0.3 on 2018-03-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolled_scans', '0007_enrolledscansentrancestep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolledscanrequirementcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='enrolledscansentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='questionnairevariantenrolledscanrequirementcondition',
            options={'base_manager_name': 'objects'},
        ),
    ]
