# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0006_auto_20160523_2147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[('SOCIAL', 'SOCIAL'), ('PARTNER', 'PARTNER')], validators=[djchoices.choices.ChoicesValidator({'PARTNER': 'PARTNER', 'SOCIAL': 'SOCIAL'})])),
                ('amount', models.PositiveIntegerField(help_text='Размер скидки')),
                ('private_comment', models.TextField(blank=True, help_text='Не показывается школьнику')),
                ('public_comment', models.TextField(blank=True, help_text='Показывается школьнику')),
                ('for_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='school.School')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Сумма к оплате')),
                ('for_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='school.School')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='paymentamount',
            unique_together=set([('for_school', 'for_user')]),
        ),
    ]
