# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20160522_1904'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfoQuestionnaireBlock',
            fields=[
                ('markdownquestionnaireblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.MarkdownQuestionnaireBlock')),
            ],
            options={
                'abstract': False,
            },
            bases=('questionnaire.markdownquestionnaireblock',),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Социальная скидка'), (2, 'Скидка от партнёра')], validators=[djchoices.choices.ChoicesValidator({1: 'Социальная скидка', 2: 'Скидка от партнёра'})]),
        ),
    ]
