# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20160523_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.PositiveIntegerField(help_text='Размер скидки. Выберите ноль, чтобы скидка считалась «рассматриваемой»'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Социальная скидка'), (2, 'Скидка от партнёра'), (3, 'Скидка от государства')], validators=[djchoices.choices.ChoicesValidator({1: 'Социальная скидка', 2: 'Скидка от партнёра', 3: 'Скидка от государства'})]),
        ),
    ]
