# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import relativefilepathfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20160522_1904'),
        ('generator', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('schools', '0008_auto_20160528_1748'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_auto_20160523_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractDocumentGenerationCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', relativefilepathfield.fields.RelativeFilePathField(path=settings.SISTEMA_FINANCE_DOCUMENTS, recursive=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('for_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
                ('for_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Используется в урлах. Лучше обойтись латинскими буквами, цифрами и подчёркиванием', max_length=100)),
                ('name', models.TextField()),
                ('for_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Document')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireVariantDocumentGenerationCondition',
            fields=[
                ('abstractdocumentgenerationcondition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.AbstractDocumentGenerationCondition')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.ChoiceQuestionnaireQuestionVariant')),
            ],
            options={
                'abstract': False,
            },
            bases=('finance.abstractdocumentgenerationcondition',),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='finance.DocumentType'),
        ),
        migrations.AddField(
            model_name='abstractdocumentgenerationcondition',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_conditions', to='finance.DocumentType'),
        ),
        migrations.AddField(
            model_name='abstractdocumentgenerationcondition',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_finance.abstractdocumentgenerationcondition_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together=set([('for_school', 'short_name')]),
        ),
    ]
