# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20160529_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='additional_information',
            field=models.TextField(blank=True, default='', help_text='Показывается школьнику перед скачиванием.Например, «Распечатайте его в двух экземплярах, подпишите со своей стороны и привезите в ЛКШ»'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='generator.Document'),
        ),
    ]
