# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20160531_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='for_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='for_users',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='documenttype',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='paymentamount',
            old_name='for_school',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='paymentamount',
            old_name='for_user',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='documenttype',
            unique_together=set([('school', 'short_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='paymentamount',
            unique_together=set([('school', 'user')]),
        ),
    ]
