# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0029_auto_20170318_1205'),
        ('finance', '0008_auto_20160725_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillPaymentInfoEntranceStep',
            fields=[
                ('fillquestionnaireentrancestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.FillQuestionnaireEntranceStep')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.fillquestionnaireentrancestep',),
        ),
    ]
