# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0047_auto_20170515_1434'),
        ('questionnaire', '0006_merge_20170523_0716'),
        ('finance', '0009_fillpaymentinfoentrancestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsEntranceStep',
            fields=[
                ('abstractentrancestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrance.AbstractEntranceStep')),
                ('text_before_start_date', models.TextField(blank=True, help_text='Текст, который показывается до даты начала заполнения шага. Поддерживается Markdown')),
                ('text_after_finish_date_if_passed', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг выполнен. Поддерживается Markdown')),
                ('text_after_finish_date_if_not_passed', models.TextField(blank=True, help_text='Текст, который показывается после даты окончания заполнения, если шаг не выполнен. Поддерживается Markdown')),
                ('text_waiting_for_other_step', models.TextField(blank=True, help_text='Текст, который показывается, когда не пройден один из предыдущих шагов. Поддерживается Markdown')),
                ('text_step_is_not_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг ещё не пройден. Поддерживается Markdown')),
                ('text_step_is_passed', models.TextField(blank=True, help_text='Текст, который показывается, когда шаг пройден пользователем. Поддерживается Markdown')),
                ('text_no_required_documents', models.TextField(help_text='Текст, который показывается, если школьнику не\xa0нужны никакие документы. Поддерживается Markdown.')),
            ],
            options={
                'abstract': False,
            },
            bases=('entrance.abstractentrancestep', models.Model),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='required_questions',
            field=models.ManyToManyField(related_name='_documenttype_required_questions_+', to='questionnaire.AbstractQuestionnaireQuestion'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_document_types', to='schools.School'),
        ),
    ]
