# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20170527_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsentrancestep',
            name='document_types',
            field=models.ManyToManyField(help_text='Документы, которые нужно сгенерировать на\xa0этом шаге', to='finance.DocumentType'),
        ),
        migrations.AlterField(
            model_name='documentsentrancestep',
            name='text_no_required_documents',
            field=models.TextField(blank=True, default='', help_text='Текст, который показывается, если школьнику не\xa0нужны никакие документы. Поддерживается Markdown.'),
        ),
    ]
