# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20170223_2302'),
        ('finance', '0011_auto_20170528_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Session'),
        ),
        migrations.AlterField(
            model_name='documentsentrancestep',
            name='document_types',
            field=models.ManyToManyField(blank=True, help_text='Документы, которые нужно сгенерировать на\xa0этом шаге', to='finance.DocumentType'),
        ),
        migrations.AlterField(
            model_name='documentsentrancestep',
            name='text_no_required_documents',
            field=models.TextField(blank=True, help_text='Текст, который показывается, если школьнику не\xa0нужны никакие документы. Поддерживается Markdown.'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='additional_information',
            field=models.TextField(blank=True, help_text='Показывается школьнику перед скачиванием.Например, «Распечатайте его в двух экземплярах, подпишите со своей стороны и привезите в ЛКШ»'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='required_questions',
            field=models.ManyToManyField(blank=True, related_name='_documenttype_required_questions_+', to='questionnaire.AbstractQuestionnaireQuestion'),
        ),
    ]
