# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20170603_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='session',
            field=models.ForeignKey(blank=True, default=None, help_text='Документ будет показан только школьникам, зачисленным в эту смену', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schools.Session'),
        ),
    ]
