# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20170618_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Социальная скидка'), (2, 'Скидка от партнёра'), (3, 'Скидка от государства'), (4, 'Олимпиадная скидка'), (5, 'Частичная оплата от\xa0организации')], validators=[djchoices.choices.ChoicesValidator({1: 'Социальная скидка', 2: 'Скидка от партнёра', 3: 'Скидка от государства', 4: 'Олимпиадная скидка', 5: 'Частичная оплата от\xa0организации'})]),
        ),
    ]
