# Generated by Django 2.0.3 on 2018-03-12 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_auto_20170620_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractdocumentgenerationcondition',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='documentsentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='fillpaymentinfoentrancestep',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paymentinfoquestionnaireblock',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='questionnairevariantdocumentgenerationcondition',
            options={'base_manager_name': 'objects'},
        ),
    ]
