# Generated by Django 2.0.3 on 2019-06-10 19:07

from django.db import migrations, models
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_auto_20180312_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentamount',
            name='currency',
            field=models.PositiveIntegerField(choices=[(0, 'Рубли'), (1, 'Евро'), (2, 'Доллар')], default=0, validators=[djchoices.choices.ChoicesValidator({0: 'Рубли', 1: 'Евро', 2: 'Доллар'})]),
            preserve_default=False,
        ),
    ]
