# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20160508_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallels', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='parallel',
            name='short_name',
            field=models.CharField(help_text='Используется в урлах. Лучше обойтись латинскими буквами, цифрами и подчёркиванием. Например, c_prime', max_length=100),
        ),
    ]
