# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20160515_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='full_name',
            field=models.TextField(help_text='Полное название, не аббревиатура. По умолчанию совпадает с обычным названием. Например, «Летняя компьютерная школа 2048»'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='Например, «ЛКШ 2048»', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='short_name',
            field=models.CharField(help_text='Используется в урлах. Например, 2048', max_length=20, unique=True),
        ),
    ]
