# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20160523_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='year',
            field=models.CharField(blank=True, help_text='Год (календарный или учебный) проведения школы.Для ЛКШ.Зима может отличаться от short_name. Может быть неуникальным', max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='full_name',
            field=models.TextField(help_text='Полное название, не аббревиатура.По умолчанию совпадает с обычным названием.Например, «Летняя компьютерная школа 2048»'),
        ),
    ]
