# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20160528_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallel',
            name='short_name',
            field=models.CharField(help_text='Используется в урлах. Лучше обойтись латинскими буквами, цифрами и подчёркиванием. Например, c_prime.', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='full_name',
            field=models.TextField(help_text='Полное название, не аббревиатура. По умолчанию совпадает с обычным названием. Например, «Летняя компьютерная школа 2048»'),
        ),
        migrations.AlterField(
            model_name='school',
            name='year',
            field=models.CharField(blank=True, help_text='Год (календарный или учебный) проведения школы. Для ЛКШ.Зима может отличаться от short_name. Может быть не уникальным.', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, help_text='Например, Август. Можно оставить пустым, если это единственная смена.', max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='short_name',
            field=models.CharField(blank=True, help_text='Используется в урлах. Лучше обойтись латинскими буквами, цифрами и подчёркиванием. Можно оставить пустым, если это единственная смена. Например, august.', max_length=20),
        ),
    ]
