# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20170115_2213'),
        ('schools', '0009_auto_20170213_0050'),
    ]

    operations = [
    ]
