# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0010_merge_20170219_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_participants', to='schools.Parallel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_participants', to='schools.School')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schoolparticipant',
            unique_together=set([('school', 'user')]),
        ),
    ]
