# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_merge_20170219_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Открыт ли доступ к школе юзерам без админских прав'),
            preserve_default=False,
        ),
    ]
