# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20170219_2232'),
        ('schools', '0011_auto_20170222_2057'),
    ]

    operations = [
    ]
