# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_merge_20170222_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolparticipant',
            name='parallel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schools.Parallel'),
        ),
        migrations.AlterField(
            model_name='schoolparticipant',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='schoolparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
