# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_auto_20170223_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Используется в урлах. Лучше обойтись латинскими буквами, цифрами и подчёркиванием. Например, c5.', max_length=100)),
                ('name', models.CharField(help_text='Например, C5', max_length=100)),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.Parallel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.Session')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('session', 'parallel', 'short_name')]),
        ),
    ]
