# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-17 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_auto_20170617_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolparticipant',
            name='parallel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schools.Parallel'),
        ),
    ]
