# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_auto_20180217_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schools.School'),
        ),
    ]
