# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settingsitem',
            unique_together=set([('short_name', 'school', 'session')]),
        ),
    ]
